### ISSUE TITLE
Question about the version of pytorch3d

### ISSUE THREAD

**Issue by zhoutianyang2002** [initialneil/SplattingAvatar#11]
great work! I am a beginner in graphics and I failed when trying to install pytorch3d through compilation. I have searched a lot of information online, but I have not found a usable solution. I think the possible reason is that pytorch3D has strict requirements for versions of pytorch, cuda, and cub. May I know the version of pytorch3d and CUB for this experiment? Sorry to bother you, I know this is a 'low' question. I have worked on deep learning before, but I didn't expect PyTorch3D to be so difficult to install. 
Thanks a lot!

**Comment by jeb0813** [comment]
Can you attach the Terminal output.
I successfully installed pytorch3D with some modifications of torch.

**Comment by zhoutianyang2002** [comment]
Thank you for your reply!
here is some basic imformation of my test: windows11, RTX4060; python3.9,cuda11.7,pytorch 1.13.1(same with the tutorial)
I had tried several times. this picture is the last error situation. 
<img width="1280" alt="Screenshot 2024-03-17 230540" src="https://github.com/initialneil/SplattingAvatar/assets/88141502/7f507bb7-6b1c-406c-9810-ca3e61ac71f2">

It also had many different errors before, e.g.
3 errors detected in the compilation of "C:/Projects/pytorch3d/pytorch3d/csrc/pulsar/cuda/renderer.backward.gpu.cu".
error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc.exe' failed with exit code 2
                        
Besides the official tutorials, I mainly referred to these blogs：
https://www.bilibili.com/read/cv32282689/?jump_opus=1
https://blog.csdn.net/m0_66227501/article/details/136423537
https://blog.csdn.net/m0_70229101/article/details/127196699

**Comment by zhoutianyang2002** [comment]
> Can you attach the Terminal output. I successfully installed pytorch3D with some modifications of torch.
Thank you for your reply!
here is some basic imformation of my test: windows11, RTX4060; python3.9,cuda11.7,pytorch 1.13.1(same with the tutorial)
I had tried several times. this picture is the last error situation. 
<img width="1280" alt="Screenshot 2024-03-17 230540" src="https://github.com/initialneil/SplattingAvatar/assets/88141502/7f507bb7-6b1c-406c-9810-ca3e61ac71f2">

It also had many different errors before, e.g.
3 errors detected in the compilation of "C:/Projects/pytorch3d/pytorch3d/csrc/pulsar/cuda/renderer.backward.gpu.cu".
error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc.exe' failed with exit code 2
                        
Besides the official tutorials, I mainly referred to these blogs：
https://www.bilibili.com/read/cv32282689/?jump_opus=1
https://blog.csdn.net/m0_66227501/article/details/136423537
https://blog.csdn.net/m0_70229101/article/details/127196699

**Comment by jeb0813** [comment]
> > Can you attach the Terminal output. I successfully installed pytorch3D with some modifications of torch.
> > Thank you for your reply!
> > here is some basic imformation of my test: windows11, RTX4060; python3.9,cuda11.7,pytorch 1.13.1(same with the tutorial)
> > I had tried several times. this picture is the last error situation.
> 
> <img alt="Screenshot 2024-03-17 230540" width="1280" src="https://private-user-images.githubusercontent.com/88141502/313483669-7f507bb7-6b1c-406c-9810-ca3e61ac71f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzI2MDEsIm5iZiI6MTcxMDczMjMwMSwicGF0aCI6Ii84ODE0MTUwMi8zMTM0ODM2NjktN2Y1MDdiYjctNmIxYy00MDZjLTk4MTAtY2EzZTYxYWM3MWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAzMjUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiOGM5ZjM2MTY3YWEyMjI3OGNiYjBkNzQ5ZjgyNDQzMjY2Y2E3ODliZGNhZDViYmE0ODY5YTU5MGRhN2QyODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.owT6Ul3X_IMwp1T4tzDgWzh8oXb9yy1WC1XBv60b1Ko">
> It also had many different errors before, e.g. 3 errors detected in the compilation of "C:/Projects/pytorch3d/pytorch3d/csrc/pulsar/cuda/renderer.backward.gpu.cu". error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc.exe' failed with exit code 2
> 
> Besides the official tutorials, I mainly referred to these blogs： https://www.bilibili.com/read/cv32282689/?jump_opus=1 https://blog.csdn.net/m0_66227501/article/details/136423537 https://blog.csdn.net/m0_70229101/article/details/127196699

sry, installation done on linux, dont know how to fix it on windows :cry:

**Comment by initialneil** [comment]
Not sure why. One possible reason: 40xx cards might require cuda 12.x.
