### ISSUE TITLE
About Pre-process

### ISSUE THREAD

**Issue by jeb0813** [initialneil/SplattingAvatar#12]
> Our preprocessing followed [IMavatar](https://github.com/zhengyuf/IMavatar/tree/main/preprocess#preprocess) and replaced the Segmentation with [RobustVideoMatting](https://github.com/PeterL1n/RobustVideoMatting).

I followed the pre-process pipeline, but I cannot get same result with the **preprocessed data**, I think there may be some issues with my replacement of segmentation.

Will the pre-process code for HeadAvatar be released?

**Comment by jeb0813** [comment]
Fix this problem with, wrong param with [RobustVideoMatting](https://github.com/PeterL1n/RobustVideoMatting).
And replaced the semantic segmentation with code in [AD-NeRF](https://github.com/YudongGuo/AD-NeRF).

Now I can obtain smiliar results. But the Camera internal parameters estimation still confuse me. :pensive:

**Comment by jeb0813** [comment]
In the pipeline of [IMavatar](https://github.com/zhengyuf/IMavatar/tree/main/preprocess#preprocess), the camera intrinsics **fx, fy, cx, cy** is calibrated by a checkerboard [#5](https://github.com/zhengyuf/IMavatar/issues/5#issuecomment-1160068258).
I borrowed the params for subject yufeng in the repo. But for other subjects, I cannot get a guess of camera intrinsics, thus I can't apply this method to new subjects. 

I wonder what method you applied to get the camera intrinsics.

Thank you.

**Comment by initialneil** [comment]
@jeb0813 A dirty solution is to directly half width/height as the cx/cy, and have a wild guess on the fov, e.g. 90 degree for regular phone lens.

**Comment by chiehwangs** [comment]
> @jeb0813 A dirty solution is to directly half width/height as the cx/cy, and have a wild guess on the fov, e.g. 90 degree for regular phone lens.

Hi, Is it possible to get the complete preprocessing script? (use RVM to segment instead of MODNet)

**Comment by jeb0813** [comment]
@chiehwangs I use the [conversion API](https://github.com/PeterL1n/RobustVideoMatting#:~:text=To%20convert%20videos%2C%20we%20provide%20a%20simple%20conversion%20API%3A) in the repo.
For some unknown reasons, I lost frames with [custom inference code](https://github.com/PeterL1n/RobustVideoMatting#:~:text=Or%20write%20your%20own%20inference%20code%3A).

So just use the API, it's simple and it's working well.

**Comment by chiehwangs** [comment]
> @chiehwangs I use the [conversion API](https://github.com/PeterL1n/RobustVideoMatting#:~:text=To%20convert%20videos%2C%20we%20provide%20a%20simple%20conversion%20API%3A) in the repo. For some unknown reasons, I lost frames with [custom inference code](https://github.com/PeterL1n/RobustVideoMatting#:~:text=Or%20write%20your%20own%20inference%20code%3A).
> 
> So just use the API, it's simple and it's working well.

Hi, thank you for your suggestion. 

Additionally, I found that [INSTA](https://github.com/Zielon/INSTA) also uses the RobustVideoMatting for portrait segmentation. By utilizing its preprocess pipeline, it's possible to obtain the same complete original image as in splattingAvatar, then fit the expression or other parameters using IMavatar. Everything is ok.

Best.

**Comment by fantasy-fish** [comment]
How about the preprocessing pipeline for the full body avatar?

**Comment by chiehwangs** [comment]
> How about the preprocessing pipeline for the full body avatar?

Sorry, I didn't try the full body.
