### ISSUE TITLE
About Novel pose

### ISSUE THREAD

**Issue by xz-pisces** [initialneil/SplattingAvatar#13]
Can you share the script on novel pose?

**Comment by initialneil** [comment]
Please see the updated eval_anim.py for novel pose.
> # to animate to noval pose `aist_demo.npz`

**Comment by amerssun** [comment]
Even after retraining on the author's openly preprocessed data, I still encountered blurry effects (on the Bala dataset). While working with the Yufeng dataset, I successfully managed to replicate the face, but rotating the head led to abnormal facial voids.
