### ISSUE TITLE
About UV

### ISSUE THREAD

**Issue by lz233-alt** [initialneil/SplattingAvatar#14]
![image](https://github.com/initialneil/SplattingAvatar/assets/71482183/8a889191-c9e3-4773-a3af-e9c2468d6dba)
I trained with Biden's picture, but the generated human head model doesn't contain UV textures, how do I get it？

**Comment by initialneil** [comment]
@lz233-alt I'm afraid that we cannot get it. It's Gaussian Splatting. To distill Gaussian Splatting to a texture atlas is an open question.
