### ISSUE TITLE
数字头能否驱动？

### ISSUE THREAD

**Issue by Tiandishihua** [initialneil/SplattingAvatar#15]

**Comment by initialneil** [comment]
@Tiandishihua Now it is animated by FLAME parameters. You might need to find a real-time FLAME tracker for this need.

**Comment by Tiandishihua** [comment]
> @Tiandishihua Now it is animated by FLAME parameters. You might need to find a real-time FLAME tracker for this need.

Can you recommend some papers related to the (real-time) FLAME tracker?

**Comment by initialneil** [comment]
@Tiandishihua Good question, I also want to know this. If you find any good FLAME trackers, please reply here. I think everybody's interested.

**Comment by gelbing** [comment]
> @Tiandishihua Good question, I also want to know this. If you find any good FLAME trackers, please reply here. I think everybody's interested.

I saw this tracker beeing used in https://github.com/aipixel/GaussianAvatar but i couldnt spin my head around it yet
https://zhangyux15.github.io/ProxyCapV2/

**Comment by initialneil** [comment]
@gelbing Thanks. I tried ROMP before, and it's not close to good. This ProxyCapV2 seems cool. Hopefully it will go open-source.
