### ISSUE TITLE
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by saba99** [initialneil/SplattingAvatar#17]
Processing ./diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects

**Comment by initialneil** [comment]
@saba99 This might be interesting to u.
https://github.com/graphdeco-inria/gaussian-splatting/issues/724
