### ISSUE TITLE
How to Use Reconstructed Avatars in Unity3D

### ISSUE THREAD

**Issue by ssup0912** [initialneil/SplattingAvatar#18]
I'd like to inquire how the authors showcased and controlled the reconstructed results in Unity3D.

**Comment by initialneil** [comment]
@ssup0912 We implemented the calculation in Unity compute shaders. You could try importing a lot of obj files or one animated fbx file into Unity for the mesh information. We tried both works. 
The key is to figure out the correct coordinates change. Be minded that the standard OpenGL is right-handed coordinate and Unity is left-handed.
