### ISSUE TITLE
Full Body Example Missing

### ISSUE THREAD

**Issue by dlazares** [initialneil/SplattingAvatar#2]
Thanks for your work and congrats on the CVPR acceptance!

The README is missing a full body example. 
Could you provide the instructions and data to reproduce the example in the video?

**Comment by initialneil** [comment]
@dlazares Thanks for your interest. 
Full-body example on PeopleSnapshot has been updated on [README](https://github.com/initialneil/SplattingAvatar?tab=readme-ov-file#full-body-avatar).

**Comment by dlazares** [comment]
Thanks for updating!

I'm gettting
```
SplattingAvatar/dataset/instant_avatar_reader.py", line 21, in read_instant_avatar_frameset
    image = np.concatenate([image, mask[:, :, None]], axis=-1)
TypeError: 'NoneType' object is not subscriptable
```

Checked it out and it looks like images and masks folders are empty in the google drive dataset.

**Comment by dlazares** [comment]
also, are you using SMPL v1.0.0 with 10 PCs or v1.1.0 with 300 PCs. from the files it looks like v1.0.0

**Comment by Connaught0** [comment]
> Thanks for updating!
> 
> I'm gettting
> 
> ```
> SplattingAvatar/dataset/instant_avatar_reader.py", line 21, in read_instant_avatar_frameset
>     image = np.concatenate([image, mask[:, :, None]], axis=-1)
> TypeError: 'NoneType' object is not subscriptable
> ```
> 
> Checked it out and it looks like images and masks folders are empty in the google drive dataset.

You might need to prepare the dataset follow the [instantAvatar](https://github.com/tijiang13/InstantAvatar). But there still are some problem, they straightly uses the original msk.npy in the instantavatar. The author need to provide the code that translate the .npy to .png.
or instead the load msk with `msk = np.load(self.msk_lists[idx])`

**Comment by dlazares** [comment]
thanks for the preprocess script! I'll try that out.

 I'm trying to reproduce from the source data as well. In the paper you mention [anim_nerf](https://github.com/JanaldoChen/Anim-NeRF) but in the config file it references [AnimatableNerf](https://github.com/zju3dv/animatable_nerf) which one did you end up using?

**Comment by initialneil** [comment]
@dlazares The SMPL poses are from https://github.com/JanaldoChen/Anim-NeRF, the same with InstantAvatar.

**Comment by ck032** [comment]
‘aist_demo.npz' is from https://github.com/tijiang13/InstantAvatar/blob/master/data/animation/aist_demo.npz

**Comment by ck032** [comment]
![0005](https://github.com/initialneil/SplattingAvatar/assets/3422807/179d4af5-7214-4409-af27-0a5406a5e5cf)
Could the full-body animation be further improved to achieve a higher level of quality ?

**Comment by initialneil** [comment]
@ck032 Please consider other scaling regularization terms from more recent papers. A large improvement would require a complete redesign.
