### ISSUE TITLE
Method of importing PLY to Unity query

### ISSUE THREAD

**Issue by trThanhnguyen** [initialneil/SplattingAvatar#33]
Hi, thanks for your great work and sharing.

I'd like to ask how did you import the resulting ```.ply``` file of the Gaussians into Unity. I've tried the Gaussian Splatting [plugin](https://github.com/aras-p/UnityGaussianSplatting) but it failed with error:
```PLY vertex size mismatch, expected 248 but file has 68.```

Any help would be appreciated.
Regards.

**Comment by initialneil** [comment]
Your ply is trained with sh=0. For Unity plugin, eighter fix Unity for less sh values or re-write the ply with more sh values filled zeros.

**Comment by trThanhnguyen** [comment]
Thank you. I can import it now. Appreciate!
