### ISSUE TITLE
Unity Project

### ISSUE THREAD

**Issue by stephan000** [initialneil/SplattingAvatar#4]
Thanks for sharing the code! Amazing work!!!

Will you release a Unity project like the one in the demo video in the near future?

**Comment by initialneil** [comment]
@stephan000 Thanks.
Sorry that due to license issue, we're not planning to release the Unity project for this paper any soon.

**Comment by stephan000** [comment]
@initialneil Thank you for your prompt reply.

I am interested in how the avatars in your work would look like in VR.
Could you tell me about your implementation in Unity, to the extent possible?

1. Is there some kind of base asset? Or is it your own implementation?
2. What steps are needed to make the avatar move as shown in the demo?
