### ISSUE TITLE
SMPL-X

### ISSUE THREAD

**Issue by LeeBeen1** [initialneil/SplattingAvatar#7]
Hi，thanks for your greating work.

The method section of the paper mentions the processing of the deformed mesh of SMPL-X, but the dataset uses SMPL. I would like to ask if this code supports the SMPL-X model?

**Comment by initialneil** [comment]
@LeeBeen1 Sorry for the typo. The `smplx_utils` in the code supports SMPL-X though. You may alter the dataloader to use SMPL-X in your own dataset. Only mesh info is needed for the rest pipeline.
