### ISSUE TITLE
How to use tool_show_3dgs_ply.py for visualization?

### ISSUE THREAD

**Issue by LiuXinqi12** [initialneil/SplattingAvatar#8]
Hi, great work! I found that the project seems to contain code for visualizing the training results, as shown in tool_show_3dgs_ply.py, but it seems that it cannot be run directly. What is the correct way to use it? Thanks!

**Comment by initialneil** [comment]
`tool_show_3dgs_ply.py` is used to show single ply file (through SIBR_remoteGaussian_app.exe)
```
# "--sh_degree" should match the actual setting for training.
python tool_show_3dgs_ply.py --ply_fn /path/to/point_cloud.ply --sh_degree 0
```

**Comment by Tiandishihua** [comment]
> `tool_show_3dgs_ply.py` is used to show single ply file (through SIBR_remoteGaussian_app.exe)
> 
> ```
> # "--sh_degree" should match the actual setting for training.
> python tool_show_3dgs_ply.py --ply_fn /path/to/point_cloud.ply --sh_degree 0
> ```

With the provided IP and port, we cannot open the web page.

**Comment by blacktears121** [comment]
> > `tool_show_3dgs_ply.py` is used to show single ply file (through SIBR_remoteGaussian_app.exe)
> > ```
> > # "--sh_degree" should match the actual setting for training.
> > python tool_show_3dgs_ply.py --ply_fn /path/to/point_cloud.ply --sh_degree 0
> > ```
> 
> With the provided IP and port, we cannot open the web page.

Hey, any update? I got the same issue. I cannot open the web page.

**Comment by initialneil** [comment]
@blacktears121 There's no web page to open. Please get familiar with the original 3DGS code first.

**Comment by fantasy-fish** [comment]
I run `python tool_show_3dgs_ply.py \
    --ply_fn ~/data/peoplesnapshot/male-3-casual/output-splatting/last_checkpoint/point_cloud/iteration_30000/point_cloud.ply \
    --sh_degree 0` and then connect through SIBR_remoteGaussian_app with the command `./SIBR_remoteGaussian_app --ip XXXX --port 6009`. The screen shows nothing.

**Comment by initialneil** [comment]
1. Please run the original 3DGS on whatever scene to get a standard point_cloud output. 
2. Use that path (`--path`) to start `SIBR_remoteGaussian_app` properly and leave it open.
3. Run `tool_show_3dgs_ply.py`.

**Comment by fantasy-fish** [comment]
> 1. Please run the original 3DGS on whatever scene to get a standard point_cloud output.
> 2. Use that path (`--path`) to start `SIBR_remoteGaussian_app` properly and leave it open.
> 3. Run `tool_show_3dgs_ply.py`.

But can I use `tool_show_3dgs_ply.py` to show 3dgs generated by SplattingAvatar?

**Comment by initialneil** [comment]
@fantasy-fish yes you can. `SIBR_remoteGaussian_app` just needs to be opened first. The initial content does not matter.

**Comment by blacktears121** [comment]
Hey @initialneil , I tried to reproduce the same, however I got this error:
[SIBR] --  INFOS  --:   Trying to connect...
[SIBR] --  INFOS  --:   Connected!
[SIBR] --  INFOS  --:   Connection dropped
[SIBR] --  INFOS  --:   Trying to connect...
[SIBR] --  INFOS  --:   Connected!
[SIBR] --  INFOS  --:   Connection dropped

and the screen on the SIBR viewer shows nothing,

any idea? thx

**Comment by initialneil** [comment]
@blacktears121 Most likely the render code crashed inside. There's a try-except in the render to camera function. You may comment out the try-except to see where it crashed

**Comment by fantasy-fish** [comment]
> @fantasy-fish yes you can. `SIBR_remoteGaussian_app` just needs to be opened first. The initial content does not matter.

The received camera information from network_gui.py [here](https://github.com/initialneil/SplattingAvatar/blob/master/gaussian_renderer/network_gui.py) shows `{'fov_x': 7.847271400218976e-43, 'fov_y': -2.216733853550873e-24, 'keep_alive': 1, 'resolution_x': 0, 'resolution_y': 0, 'rot_scale_python': 0, 'scaling_modifier': 1.0, 'shs_python': 0, 'train': 1, 'view_matrix': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'view_projection_matrix': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'z_far': 7.847271400218976e-43, 'z_near': 2.802596928649634e-45}`. It seems not very correct

**Comment by blacktears121** [comment]
@fantasy-fish got the same error. 
![image](https://github.com/user-attachments/assets/2e415107-af6c-413b-9a8d-ab2e5ca56b60)

**Comment by blacktears121** [comment]
@initialneil any update? thx
