### ISSUE TITLE
Qustion about visualization

### ISSUE THREAD

**Issue by HenryKang1** [initialneil/SplattingAvatar#9]
Hello. I check the issue and you could not share the Unity tools. I am wondering what output should I use to make 4D video and visualize it? I am quite new about 3D stuff. I check the SIBR_remoteGaussian_app tool but I do not have config_args file. It gives me error.  Also this tools for the 1 frame moment based on your other issue. Which file should I dig and make the 4D video?
I check your evaluation code and it only compare the image to image. 
I believe that "render_pkg " looks like key. what information should I utilize it?

**Comment by initialneil** [comment]
@HenryKang1 To use SIBR_remoteGaussian_app, run the original gaussian splatting training on any original data. Then you have a path to give to SIBR_remoteGaussian_app.

**Comment by fantasy-fish** [comment]
Is there any way to visualize this in the SIBR_remoteGaussian_app?
